# -*- coding: utf-8 -*-
"""github

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qG3GiZ7tYmo7Gq7Fl4h1EkvZpSBE0260
"""

!apt-get install git

!git clone https://github.com/zainalysis/Cricket-Run-Predictor.git

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

#Step 2: Import necessary libraries

import pandas as pd
#Step 3: Define the path to your CSV file

file_path = '/content/drive/My Drive/modelpred.csv'
#Step 4: Read the CSV file into a DataFrame

data = pd.read_csv(file_path)

# To check for missing values
print(data.isnull().sum())

# Drop any rows with missing values (if any)
data = data.dropna()

# Extract necessary columns
X = data[['inns_rr', 'inns_wkts', 'inns_balls_rem']]
y = data['batruns']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Save the model
import joblib
joblib.dump(model, 'run_prediction_model.pkl')

pip install streamlit

!pip install streamlit pyngrok

!pip install streamlit
!pip install pyngrok

import streamlit as st
import joblib

# Load the model
model = joblib.load('run_prediction_model.pkl')

# Create the Streamlit app
st.title("Cricket Run Prediction")

# Take user input
inns_rr = st.number_input("Innings Run Rate (before the ball)")
inns_wkts = st.number_input("Wickets down (before the ball)")
inns_balls_rem = st.number_input("Balls remaining (in the innings)")

# When the 'Predict' button is clicked
if st.button('Predict'):
    # Create input data for prediction
    input_data = [[inns_rr, inns_wkts, inns_balls_rem]]

    # Make prediction
    predicted_runs = model.predict(input_data)

    # Display the result
    st.write(f"Expected Runs for the next ball: {predicted_runs[0]:.2f}")

from google.colab import files
uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/My Drive/Colab Notebooks/github.ipynb')